"""File inventory: safe repository scanning with filtering and limits.

This implements the "large repository support" and security requirements:
.gitignore support, generated-file detection, binary detection, file-size
limits, and a hard cap on total files — without ever loading entire files.
"""

from __future__ import annotations

import os
from pathlib import Path

from app.analyzers.source_graph import FileCategory, FileEntry
from app.core.config import get_settings

# Files/dirs that are never analyzed.
_DEFAULT_IGNORES = {
    ".git",
    ".hg",
    ".svn",
    "__pycache__",
    "node_modules",
    ".venv",
    "venv",
    "env",
    ".tox",
    ".mypy_cache",
    ".pytest_cache",
    ".idea",
    ".vscode",
    "dist",
    "build",
    "target",
    "vendor",
    ".next",
    ".nuxt",
    "coverage",
    "htmlcov",
    ".cache",
    "Pods",
    ".gradle",
}

# Extensions that are always treated as binary/non-text.
_BINARY_EXTENSIONS = {
    ".png", ".jpg", ".jpeg", ".gif", ".webp", ".ico", ".bmp", ".svgz",
    ".pdf", ".zip", ".gz", ".tar", ".tgz", ".rar", ".7z", ".bz2", ".xz",
    ".woff", ".woff2", ".ttf", ".otf", ".eot",
    ".exe", ".dll", ".so", ".dylib", ".bin", ".dat", ".pyc", ".pyo",
    ".class", ".jar", ".war", ".o", ".a", ".lib", ".obj",
    ".mp3", ".mp4", ".avi", ".mov", ".mkv", ".wav", ".flac",
    ".db", ".sqlite", ".sqlite3", ".mdb",
}

_TEXT_EXTENSIONS = {
    ".py", ".js", ".jsx", ".ts", ".tsx", ".go", ".rs", ".java", ".cs", ".cpp",
    ".c", ".h", ".hpp", ".dart", ".php", ".rb", ".kt", ".kts", ".swift",
    ".scala", ".sh", ".bash", ".zsh", ".fish", ".ps1", ".bat", ".cmd",
    ".md", ".markdown", ".rst", ".txt", ".yaml", ".yml", ".toml", ".ini",
    ".cfg", ".conf", ".json", ".xml", ".html", ".htm", ".css", ".scss",
    ".sass", ".less", ".vue", ".svelte", ".sql", ".graphql", ".gql",
    ".proto", ".env", ".dockerfile", ".makefile", ".mk", ".cmake",
    ".tf", ".yml", ".gradle", ".properties", ".lock",
}

_GENERATED_MARKERS = (
    "generated by",
    "auto-generated",
    "do not edit",
    "code generated",
    "@generated",
    "this file is generated",
)


def _read_gitignore(root: Path) -> list[str]:
    """Read .gitignore patterns (simple, line-based)."""
    patterns: list[str] = []
    gi = root / ".gitignore"
    if gi.is_file():
        try:
            for line in gi.read_text(encoding="utf-8", errors="ignore").splitlines():
                line = line.strip()
                if line and not line.startswith("#"):
                    patterns.append(line.rstrip("/"))
        except OSError:
            pass
    return patterns


def _matches_ignore(rel: str, patterns: list[str]) -> bool:
    parts = rel.replace("\\", "/").split("/")
    for p in patterns:
        p = p.strip("/")
        if not p:
            continue
        if p in parts:
            return True
        # simple suffix/glob
        if p.endswith("/*") and rel.startswith(p[:-1]):
            return True
        if p.startswith("*.") and rel.endswith(p[1:]):
            return True
        if p == rel or rel.startswith(p + "/"):
            return True
    return False


def classify_file(path: Path, size: int) -> tuple[FileCategory, str, bool]:
    """Classify a file into a category + language, and detect binary."""
    name = path.name
    lower = name.lower()
    ext = path.suffix.lower()

    if ext in _BINARY_EXTENSIONS:
        return FileCategory.ASSET, "", True

    # Language detection via extension.
    language = _EXT_TO_LANG.get(ext, "")

    # Category inference.
    if ext in {".md", ".markdown", ".rst"} or lower in {"readme", "readme.md"}:
        category = FileCategory.DOC
    elif lower in {"dockerfile"} or ext in {".yml", ".yaml", ".toml", ".ini", ".cfg", ".conf", ".env"}:
        category = FileCategory.CONFIG
    elif name in {"requirements.txt", "package.json", "go.mod", "go.sum", "cargo.toml",
                  "pom.xml", "build.gradle", "pyproject.toml", "setup.py", "gemfile",
                  "composer.json", "pubspec.yaml"}:
        category = FileCategory.CONFIG
    elif "test" in lower or lower.endswith("test.py") or lower.startswith("test_"):
        category = FileCategory.TEST
    elif ext in _TEXT_EXTENSIONS and language:
        category = FileCategory.SOURCE
    elif ext in _TEXT_EXTENSIONS:
        category = FileCategory.OTHER
    else:
        category = FileCategory.OTHER

    return category, language, False


_EXT_TO_LANG = {
    ".py": "python",
    ".js": "javascript",
    ".jsx": "javascript",
    ".ts": "typescript",
    ".tsx": "typescript",
    ".go": "go",
    ".rs": "rust",
    ".java": "java",
    ".cs": "csharp",
    ".cpp": "cpp",
    ".c": "c",
    ".h": "c",
    ".hpp": "cpp",
    ".dart": "dart",
    ".php": "php",
    ".rb": "ruby",
    ".kt": "kotlin",
    ".kts": "kotlin",
    ".swift": "swift",
    ".scala": "scala",
    ".sh": "shell",
    ".bash": "shell",
    ".vue": "vue",
    ".svelte": "svelte",
    ".css": "css",
    ".scss": "scss",
    ".html": "html",
    ".htm": "html",
    ".sql": "sql",
}


class FileInventory:
    """Scans a repository directory into a filtered list of FileEntry objects."""

    def __init__(self, root: str) -> None:
        self.root = Path(root)
        self.settings = get_settings()

    def scan(self) -> list[FileEntry]:
        gitignore = _read_gitignore(self.root)
        entries: list[FileEntry] = []
        for dirpath, dirnames, filenames in os.walk(self.root):
            # Prune ignored directories in-place.
            dirnames[:] = [
                d for d in dirnames
                if d not in _DEFAULT_IGNORES
                and not _matches_ignore(
                    str(Path(dirpath) / d).replace(str(self.root), "").lstrip("\\/"), gitignore
                )
            ]
            for fname in filenames:
                fpath = Path(dirpath) / fname
                rel = str(fpath.relative_to(self.root)).replace("\\", "/")
                if _matches_ignore(rel, gitignore):
                    continue
                try:
                    size = fpath.stat().st_size
                except OSError:
                    continue
                category, language, is_binary = classify_file(fpath, size)
                if size > self.settings.max_file_size_bytes:
                    # Oversized: skip content but record for reporting.
                    entries.append(FileEntry(
                        path=rel, category=category, language=language,
                        size=size, is_binary=True,
                    ))
                    continue
                entries.append(FileEntry(
                    path=rel, category=category, language=language,
                    size=size, is_binary=is_binary,
                ))
                if len(entries) >= self.settings.max_files_per_analysis:
                    break
            if len(entries) >= self.settings.max_files_per_analysis:
                break
        return entries

    @staticmethod
    def source_files(entries: list[FileEntry]) -> list[FileEntry]:
        return [e for e in entries if e.category == FileCategory.SOURCE and not e.is_binary]

    @staticmethod
    def config_files(entries: list[FileEntry]) -> list[FileEntry]:
        return [e for e in entries if e.category == FileCategory.CONFIG]

    @staticmethod
    def test_files(entries: list[FileEntry]) -> list[FileEntry]:
        return [e for e in entries if e.category == FileCategory.TEST]

    @staticmethod
    def doc_files(entries: list[FileEntry]) -> list[FileEntry]:
        return [e for e in entries if e.category == FileCategory.DOC]
